package com.oingmaryho.business.companyservice.application;

import org.mapstruct.factory.Mappers;

import com.oingmaryho.business.companyservice.application.dto.response.CompanyCreateResponseServiceDto;
import com.oingmaryho.business.companyservice.application.dto.response.CompanyDetailsSearchResponseServiceDto;
import com.oingmaryho.business.companyservice.application.dto.response.CompanySearchResponseServiceDto;
import com.oingmaryho.business.companyservice.application.dto.response.CompanyUpdateResponseServiceDto;
import com.oingmaryho.business.companyservice.presentation.dto.response.CompanyCreateResponseDto;
import com.oingmaryho.business.companyservice.presentation.dto.response.CompanyDetailsSearchResponseDto;
import com.oingmaryho.business.companyservice.presentation.dto.response.CompanySearchResponseDto;
import com.oingmaryho.business.companyservice.presentation.dto.response.CompanyUpdateResponseDto;

public interface CompanyApplicationMapper {
	CompanyApplicationMapper INSTANCE = Mappers.getMapper(CompanyApplicationMapper.class);

	CompanyCreateResponseDto toCreateResponseDto(CompanyCreateResponseServiceDto companyCreateResponseServiceDto);

	CompanyDetailsSearchResponseDto toDetailsSearchResponseDto(
		CompanyDetailsSearchResponseServiceDto companyDetailsSearchResponseServiceDto);

	CompanySearchResponseDto toSearchResponseDto(CompanySearchResponseServiceDto companySearchResponseServiceDto);

	CompanyUpdateResponseDto toUpdateResponseDto(CompanyUpdateResponseServiceDto companyUpdateResponseServiceDto);
}
